[package]
name = "service-model"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { path = "../db", package = "service-db" }

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
